# This variable requests the highest version of 
# Visual Studio to be installed. Previous versions
# will also be available and work. So, choosing 2015 here makes
# available both `msvs_toolset: 12` (from Visual Studio 2013)
# and `msvs_toolset: 14` (from Visual Studio 2015)
# Note/TODO: it is not yet confirmed that earlier versions work with the the `Visual Studio 2017` os image. 
os: Visual Studio 2015

environment:
  node_pre_gyp_accessKeyId:
    secure: 7DrSVc5eIGtmMcki5H+iRft+Tk3MJTwDBQEUuJHWaQ4=
  node_pre_gyp_secretAccessKey:
    secure: 1amwJJw9fu0j6dXnc5KsAQbSYf7Cjw/dapT6OZWABa6nc52grkKeLQ+DGaOfQz8i
  matrix:
    - nodejs_version: 0.10
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 0.10
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 4
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 4
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 4
      platform: x86
      msvs_toolset: 14
    - nodejs_version: 4
      platform: x64
      msvs_toolset: 14
    - nodejs_version: 6
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 6
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 6
      platform: x86
      msvs_toolset: 14
    - nodejs_version: 6
      platform: x64
      msvs_toolset: 14
    - nodejs_version: 8
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 8
      platform: x64
      msvs_toolset: 14
    - nodejs_version: 8
      platform: x86
      msvs_toolset: 14
    - nodejs_version: 8
      platform: x64
      msvs_toolset: 14

install:
  - ps: Start-FileDownload 'https://github.com/mapbox/ci-scripts/raw/v1.1.0/node/ci-cpp.bat' -FileName ci.bat
  - CALL ci.bat

build: OFF
test: OFF
deploy: OFF
